Disable elisp-lint by default (fixes #22)
doublep/eldev pull request #23
Opened 2020-09-22 01:41 UTC by sirikid

2020-09-26 16:55 UTC, doublep requested changes

2020-09-26 16:55 UTC, doublep commented on eldev.el
> +        Cleaner name (a symbol) for ther command line.  Default
Forgot to change to "Linter name".

2020-09-26 16:55 UTC, doublep commented on eldev.el
> +  :default        nil
Just remove this line, it's fine to rely on `nil` being the default.

2020-09-26 18:29 UTC, sirikid commented on eldev.el
> +        Cleaner name (a symbol) for ther command line.  Default
Lol

2020-09-28 21:48 UTC, doublep approved these changes

2020-09-28 21:51 UTC, doublep requested changes

2020-09-28 21:51 UTC, doublep commented on eldev.el
> +         (:default (assq :default (assq linter eldev--linters)))
As it stands, I get the following if I try running it:

    ~/eldev$ eldev lint
    Wrong type argument: listp, (elisp . eldev-linter-elisp)

2020-09-30 01:51 UTC, sirikid commented
I think I fixed it, but I didn't add the test.

2020-09-30 20:37 UTC, doublep approved these changes

2020-09-30 20:38 UTC, merged

2020-09-30 20:39 UTC, doublep commented
> but I didn't add the test

Doesn't seem to be really needed here, so it's OK.

Seems to work fine now. Also doesn't break Cider.

Merged, thank you.